import { groupWorldStatusByDC } from './module';

const testDataCenters = {"Aether":["Adamantoise","Cactuar","Faerie","Gilgamesh","Jenova","Midgardsormr","Sargatanas","Siren"],"Chaos":["Cerberus","Louisoix","Moogle","Omega","Phantom","Ragnarok","Sagittarius","Spriggan"],"Crystal":["Balmung","Brynhildr","Coeurl","Diabolos","Goblin","Malboro","Mateus","Zalera"],"Dynamis":["Halicarnassus","Maduin","Marilith","Seraph"],"Elemental":["Aegis","Atomos","Carbuncle","Garuda","Gungnir","Kujata","Tonberry","Typhon"],"Gaia":["Alexander","Bahamut","Durandal","Fenrir","Ifrit","Ridill","Tiamat","Ultima"],"Korea":["\ucd08\ucf54\ubcf4","\ubaa8\uadf8\ub9ac","\uce74\ubc99\ud074","\ud1a4\ubca0\ub9ac","\ud39c\ub9ac\ub974"],"Light":["Alpha","Lich","Odin","Phoenix","Raiden","Shiva","Twintania","Zodiark"],"Mana":["Anima","Asura","Chocobo","Hades","Ixion","Masamune","Pandaemonium","Titan"],"Materia":["Bismarck","Ravana","Sephirot","Sophia","Zurvan"],"Meteor":["Belias","Mandragora","Ramuh","Shinryu","Unicorn","Valefor","Yojimbo","Zeromus"],"Primal":["Behemoth","Excalibur","Exodus","Famfrit","Hyperion","Lamia","Leviathan","Ultros"],"\u732b\u5c0f\u80d6":["ZiShuiZhanQiao","YanXia","JingYuZhuangYuan","MoDuNa","HaiMaoChaWu","RouFengHaiWan","HuPoYuan"],"\u83ab\u53e4\u529b":["BaiYinXiang","BaiJinHuanXiang","ShenQuanHen","ChaoFengTing","LvRenZhanQiao","FuXiaoZhiJian","Longchaoshendian","MengYuBaoJing"],"\u8c46\u8c46\u67f4":["ShuiJingTa2","YinLeiHu2","TaiYangHaiAn2","YiXiuJiaDe2","HongChaChuan2"],"\u9646\u884c\u9e1f":["HongYuHai","ShenYiZhiDi","LaNuoXiYa","HuanYingQunDao","MengYaChi","YuZhouHeYin","WoXianXiRan","ChenXiWangZuo"]};
const testWorldStatus = {"Atomos":1,"Bahamut":1,"Chocobo":1,"Mandragora":1,"Tiamat":1,"Tonberry":1,"Garuda":1,"Ifrit":1,"Ramuh":1,"Titan":1,"Adamantoise":1,"Behemoth":1,"Cactuar":1,"Cerberus":1,"Coeurl":1,"Goblin":1,"Malboro":1,"Moogle":1,"Ultros":1,"Diabolos":1,"Gilgamesh":1,"Leviathan":1,"Midgardsormr":1,"Odin":1,"Shiva":1,"Ridill":1,"Masamune":1,"Durandal":1,"Aegis":1,"Gungnir":1,"Sargatanas":1,"Balmung":1,"Hyperion":1,"Excalibur":1,"Ragnarok":1,"Alexander":1,"Anima":1,"Carbuncle":1,"Fenrir":1,"Hades":1,"Ixion":1,"Kujata":1,"Typhon":1,"Ultima":1,"Valefor":1,"Exodus":1,"Faerie":1,"Lamia":1,"Phoenix":1,"Siren":1,"Pandaemonium":1,"Unicorn":1,"Yojimbo":1,"Famfrit":1,"Lich":1,"Mateus":1,"Asura":1,"Belias":1,"Zeromus":1,"Brynhildr":1,"Zalera":1,"Shinryu":1,"Twintania":1,"Omega":1,"Jenova":1,"Zodiark":1,"Louisoix":1,"Spriggan":1,"Bismarck":1,"Ravana":1,"Sephirot":1,"Sophia":1,"Zurvan":1,"Sagittarius":1,"Phantom":1,"Alpha":1,"Raiden":1,"Marilith":1,"Seraph":1,"Halicarnassus":1,"Maduin":1};

describe('groupWorldStatusByDC', () => {
  it('should show the data centers', () => {
    groupWorldStatusByDC(testDataCenters, testWorldStatus);
    expect(true).toBeTruthy();
  })
});